version: '3.9'

services:
  telegram-bot:
    build: .
    volumes:
      - .:/usr/src/app
    restart: always # docker restart if it crash
    networks:
      - network
#     ports:
#       - "0000:0000"
#     volumes:
#       - bot_data:/var/lib/bot/data
volumes:
  bot_data:

networks:
  network:
    driver: bridge
