"""Initial migration

Revision ID: 0c22671a0711
Revises: 
Create Date: 2024-02-07 11:21:41.018630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c22671a0711'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Float(precision=30), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_db_id'), 'users_db', ['id'], unique=False)
    op.create_table('users_telegram',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_block', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_good', sa.Integer(), server_default='3', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users_telegram', ['id'], unique=True)
    op.create_table('discussion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discus', sa.String(length=7000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users_telegram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('temp_chat', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('frequency', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('presence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('flag_stik', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('all_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('all_token', sa.Integer(), server_default='0', nullable=False),
    sa.Column('the_gap', sa.Float(), server_default='0.05', nullable=False),
    sa.Column('set_model', sa.String(length=50), server_default='gpt-3.5-turbo-0613', nullable=False),
    sa.Column('give_me_money', sa.Float(), server_default='0', nullable=False),
    sa.Column('money', sa.Float(), server_default='100', nullable=False),
    sa.Column('all_in_money', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users_telegram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('use_model', sa.String(length=50), nullable=False),
    sa.Column('sesion_token', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price_1_tok', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_sesion_tok', sa.Float(), server_default='0', nullable=False),
    sa.Column('users_telegram_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['users_telegram_id'], ['users_telegram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_users_telegram_id'), 'statistics', ['users_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_users_telegram_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_table('settings')
    op.drop_table('discussion')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users_telegram')
    op.drop_table('users_telegram')
    op.drop_index(op.f('ix_users_db_id'), table_name='users_db')
    op.drop_table('users_db')
    op.drop_table('exchange')
    # ### end Alembic commands ###
