"""Initial migration

Revision ID: efe1625607dc
Revises: 
Create Date: 2024-01-17 19:09:50.943466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe1625607dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('models_chat', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patch_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_chat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users_telegram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_first_name', sa.String(length=50), nullable=True),
    sa.Column('user_last_name', sa.String(length=50), nullable=True),
    sa.Column('user_username', sa.String(length=50), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('is_user_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_user_block', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_user_good', sa.Integer(), server_default='3', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chatgpt_setings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_chat', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('lang_chat', sa.String(length=15), server_default='RU', nullable=False),
    sa.Column('count_req_chat', sa.Integer(), nullable=True),
    sa.Column('used_token_chat', sa.Integer(), nullable=True),
    sa.Column('limit_token_chat', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('patch_chat', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users_telegram.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models_chat.id'], ),
    sa.ForeignKeyConstraint(['patch_chat'], ['patch_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=2000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('users_telegram_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_telegram_id'], ['users_telegram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=2000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['saved_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_answer')
    op.drop_table('saved_questions')
    op.drop_table('chatgpt_setings')
    op.drop_table('users_telegram')
    op.drop_table('users')
    op.drop_table('patch_chat')
    op.drop_table('models_chat')
    # ### end Alembic commands ###
